### ISSUE TITLE
Browser socket.io-stream

### ISSUE THREAD

**Issue by maeuca** [nkzawa/socket.io-stream#14]
Hello,  I'm trying to use socket.io-stream in a browser to upload a file.  However, I keep getting this error, in the file change event.

"Uncaught ReferenceError: ss is not defined "

Am I missing something obvious?  Please help.

Thanks in advance.

Here is the html source:

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <script type="text/javascript" src="/socket.io/socket.io.js"></script>
    <script type="text/javascript" src="/js/socket.io-stream.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
     <script>
        $(function() {
            $('#file').change(function(e) {
                var file = e.target.files[0];
                var stream = ss.createStream();

```
            // upload a file to the server.
            ss(socket).emit('file', stream, {size: file.size});
            ss.createBlobReadStream(file).pipe(stream);
        });
    });
    var socket = io.connect('http://lb1:8080');

</script>
```

</head>
<body>

<hr>

<input id="file" type="file" />

</body>
</html>

**Comment by mukeshkanyal** [comment]
it showing browserify:command not found when i'm run this command in terminal browserify index.js -s ss > socket.io-stream.js
