### ISSUE TITLE
Not handled stream can block stream for other clients?

### ISSUE THREAD

**Issue by peteruithoven** [nkzawa/socket.io-stream#36]
I'm trying to forward a file over socket.io-stream to multiple clients. But when the same stream is piped to two socket.io-stream clients, I notices that if one client doesn't handle the event (or use the stream) the other client can't fully retrieve the stream either. 
I've tried to create an as simple as possible example. 
How should I handle this? Am I trying to do something impossible? 
I can't just add another read stream because in my actual use case that stream is another socket.io-stream that is send to the server.  
To clarify, when both clients listen (handle the event and the stream) it works fine. 

``` javascript
var socketClient  = require('socket.io-client');
var debug         = require('debug')('streams');
var ss            = require("socket.io-stream");
var fs            = require('fs');
var PORT          = 5000;
var URL           = "http://localhost:"+PORT;

server();
consumer("a",true);
consumer("b",false);

// SERVER
function server() {
  var http          = require('http').Server();
  var io            = require('socket.io')(http);
  http.listen(PORT, function(){
    debug('server listening on *:' + PORT);
  });
  var nsp = io.of('/');
  var consumers = [];
  nsp.on('connection', function(socket) {
    var query = socket.handshake.query;
    debug("server: new connection: ",query.name);
    consumers.push(ss(socket));
  });
  setTimeout(function() {
    var filename = "image.jpg";
    var readStream = fs.createReadStream("assets/"+filename);
    for(var i in consumers) {
      var outgoingStream = ss.createStream();
      consumers[i].emit('file',outgoingStream,{name:filename});
      readStream.pipe(outgoingStream);
    } 
  },500); 
}

// CLIENTS
function consumer(name,listen) {
  var serverSocket = socketClient(URL+"?name="+name,{forceNew:true});
  var serverStreamSocket = ss(serverSocket);
  serverSocket.once('connect', function(){
    debug("consumer "+name+" connected");
    if(listen) {
      serverStreamSocket.on("file",function(stream,data) {
        debug("consumer on file");
        stream.pipe(fs.createWriteStream(name+"-"+data.name));
      });
    }
  });
}
```

**Comment by peteruithoven** [comment]
Using resume to put the stream into flowing mode works for me, so I'll close this issue.

**Comment by waltergms** [comment]
How do i stop stream withou disconnect client socket? Im using the ss on a chat system and i cant disconect the client, i just have to give a option to the client cancel the upload before it ends....

**Comment by peteruithoven** [comment]
Isn't this a separate question? Why not call the `end()` on the stream instance?

**Comment by jenil04** [comment]
I'm trying to transfer and store files from one socket to another. The stored files are saved in a Merkle tree. How do I save this data stream into a merkle tree?
