### ISSUE TITLE
How to browserify socket.io-stream.js?

### ISSUE THREAD

**Issue by xiaoshao** [nkzawa/socket.io-stream#45]
I do it as your introduce on the README to browserify. But When I reference it with src = '/js/socket.io-stream.js' or 'socket.io-stream/socket.io-stream.js', My browser complain that can't get the resource. 

note:  I start my server with node app.js. 

var app = require("express")();
var http = require("http").Server(app);
var io = require("socket.io")(http);
var fs = require("fs");
//var ss = require("socket.io-steam");
var sockets = {};

app.get("/", function (req, resp) {
    resp.sendFile(__dirname + "/view/message.html");
});

http.listen(3000, function () {
    console.log("listening on 3000");
});

**Comment by nkzawa** [comment]
Where did you create the file? It has to be accessible from browser.

**Comment by xiaoshao** [comment]
I have to add app.get('/socket.io-stream.js', function().....); in order my browser can get socket.io-stream.js.

**Comment by nkzawa** [comment]
looks solved :)
