### ISSUE TITLE
Unexpected behavior for BlobStream pause and resume?

### ISSUE THREAD

**Issue by jonathanasquier** [nkzawa/socket.io-stream#47]
Hello,
I'm having issues pausing and resuming the stream upload using BlobStream.pause() and and BlobStream.resume(). I read BlobStream returned a Readable Stream and that these methods were implemented. Pause does nothing, and resume emits 1 data event and pauses.

Have I missed something ? What would be the best way to pause and resume a stream upload?

Thanks a lot! :)

**Comment by nkzawa** [comment]
Maybe your stream is in paused mode? I'm not sure but `#pause()` looks a method for flowing mode.
Or can you post your code which we can reproduce the issue if possible?

**Comment by vheuken** [comment]
I am having a similar issue. Pause works, but resume emits 1 data event and then pauses.

Here's my hacky solutuon:
```javascript
blobStream.on("data", function() { this.resume() });
```

**Comment by vheuken** [comment]
Actually, that wasn't a solution. Worked fine locally, but when I threw it on a remote server it didn't work. Turns out I had to unpipe the stream to pause, then re-pipe it to resume.
